### ISSUE TITLE
Удали гитхаб клякса ебаная

### ISSUE THREAD

**Issue by just-noname-bing** [Ja1z666/portfolio-website#2]
https://github.com/Ja1z666/portfolio-website/blob/646ab0b4c2f960dea8222fc08f506cb56991cdee/src/pages/components/scene.tsx#L28

я твой рот ебал посредственность нахуй. Все твои действия приводят к взрыву африки хуесос

пидорас 

твою маму должны были перерезать на 3 куска

**Comment by Ja1z666** [comment]
хахахаха
